//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanSteam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DonDatHangNCC
    {
        public int MaCT_DonDatHangNCC { get; set; }
        public int MaDonDatHangNCC { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> DonGiaDat { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual DonDatHangNCC DonDatHangNCC { get; set; }
        public virtual THONGTINSANPHAM THONGTINSANPHAM { get; set; }
    }
}
