//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanSteam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAPHANG
    {
        public int MaCTPhieuNhapHang { get; set; }
        public int MaSanPham { get; set; }
        public int MaPhieuNhapHang { get; set; }
        public Nullable<int> Sluong { get; set; }
        public Nullable<double> DonGiaNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
        public virtual THONGTINSANPHAM THONGTINSANPHAM { get; set; }
    }
}
