//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanSteam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHangNCC
    {
        public DonDatHangNCC()
        {
            this.CT_DonDatHangNCC = new HashSet<CT_DonDatHangNCC>();
        }
    
        public int MaDonDatHangNCC { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> TongSL { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<CT_DonDatHangNCC> CT_DonDatHangNCC { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
    }
}
