//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanSteam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public LIENHE()
        {
            this.DOITRAs = new HashSet<DOITRA>();
        }
    
        public int MaLH { get; set; }
        public Nullable<int> MaPhieuDH { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnhHD { get; set; }
        public string HinhAnhSP { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<DOITRA> DOITRAs { get; set; }
        public virtual PHIEUDATHANG PHIEUDATHANG { get; set; }
    }
}
