//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanSteam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public SALE()
        {
            this.SPSALEs = new HashSet<SPSALE>();
        }
    
        public int MASL { get; set; }
        public string TENSL { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
    
        public virtual ICollection<SPSALE> SPSALEs { get; set; }
    }
}
