//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanSteam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QL_THIETBISTEAMEntities1 : DbContext
    {
        public QL_THIETBISTEAMEntities1()
            : base("name=QL_THIETBISTEAMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CT_DonDatHangNCC> CT_DonDatHangNCC { get; set; }
        public DbSet<CT_PHIEUDATHANG> CT_PHIEUDATHANG { get; set; }
        public DbSet<CT_PHIEUNHAPHANG> CT_PHIEUNHAPHANG { get; set; }
        public DbSet<DOITRA> DOITRAs { get; set; }
        public DbSet<DonDatHangNCC> DonDatHangNCCs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LIENHE> LIENHEs { get; set; }
        public DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHANQUYEN> PHANQUYENs { get; set; }
        public DbSet<PHIEUDATHANG> PHIEUDATHANGs { get; set; }
        public DbSet<PHIEUGIAOHANG> PHIEUGIAOHANGs { get; set; }
        public DbSet<PHIEUNHAPHANG> PHIEUNHAPHANGs { get; set; }
        public DbSet<SALE> SALEs { get; set; }
        public DbSet<SPSALE> SPSALEs { get; set; }
        public DbSet<THONGTINSANPHAM> THONGTINSANPHAMs { get; set; }
        public DbSet<TINHTRANGDH> TINHTRANGDHs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int Update_SL_Ton(Nullable<int> maCTPhieuNhapHang, Nullable<int> maSP, Nullable<int> maPhieuNhapHang)
        {
            var maCTPhieuNhapHangParameter = maCTPhieuNhapHang.HasValue ?
                new ObjectParameter("MaCTPhieuNhapHang", maCTPhieuNhapHang) :
                new ObjectParameter("MaCTPhieuNhapHang", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var maPhieuNhapHangParameter = maPhieuNhapHang.HasValue ?
                new ObjectParameter("MaPhieuNhapHang", maPhieuNhapHang) :
                new ObjectParameter("MaPhieuNhapHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_SL_Ton", maCTPhieuNhapHangParameter, maSPParameter, maPhieuNhapHangParameter);
        }
    
        public virtual int Update_TongSL_DatHangNCC(string maDonDHNCC)
        {
            var maDonDHNCCParameter = maDonDHNCC != null ?
                new ObjectParameter("MaDonDHNCC", maDonDHNCC) :
                new ObjectParameter("MaDonDHNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TongSL_DatHangNCC", maDonDHNCCParameter);
        }
    
        public virtual int Update_TongSL_PN(string maPhieuNH)
        {
            var maPhieuNHParameter = maPhieuNH != null ?
                new ObjectParameter("MaPhieuNH", maPhieuNH) :
                new ObjectParameter("MaPhieuNH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TongSL_PN", maPhieuNHParameter);
        }
    
        public virtual int Update_TongTien_DatHangNCC(string maDonDHNCC)
        {
            var maDonDHNCCParameter = maDonDHNCC != null ?
                new ObjectParameter("MaDonDHNCC", maDonDHNCC) :
                new ObjectParameter("MaDonDHNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TongTien_DatHangNCC", maDonDHNCCParameter);
        }
    
        public virtual int Update_TongTien_PN(string maPhieuNH)
        {
            var maPhieuNHParameter = maPhieuNH != null ?
                new ObjectParameter("MaPhieuNH", maPhieuNH) :
                new ObjectParameter("MaPhieuNH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TongTien_PN", maPhieuNHParameter);
        }
    
        public virtual int Update_TrangThai_DatHangNCC(Nullable<int> maDonDHNCC)
        {
            var maDonDHNCCParameter = maDonDHNCC.HasValue ?
                new ObjectParameter("MaDonDHNCC", maDonDHNCC) :
                new ObjectParameter("MaDonDHNCC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_TrangThai_DatHangNCC", maDonDHNCCParameter);
        }
    }
}
